### ISSUE TITLE
Label files in a folder cause fatal error

### ISSUE THREAD

**Issue by merrill-oakland** [open-lms-open-source/moodle-tool_ally#47]
If you have an image in a file in a course label that isn't stored in the root level of the files area (like if you have an image in a folder), it results in a fatal error, preventing the display of the course.
<img width="1127" alt="Screen Shot 2020-08-10 at 3 06 13 PM" src="https://user-images.githubusercontent.com/1144470/89820610-4e26ff80-db1b-11ea-9980-2ee5c630d8ef.png">

The basic problem though is that tool_ally\local_file::get_fileurlproperties() makes incorrect assumptions about decoding pluginfile paths. Namely it assumes that counting the number of parts can tell you what each of those parts is. That is *not* true. In particular, if we have the path `pluginfile.php/6168571/mod_label/intro/Test/Coin.png`, get_fileurlproperties() assumes that because there are 3 path parts after the component, then it must be an itemid, not a path.

To properly decode this, you would instead need to use /lib/filelib.php::file_pluginfile() as a reference. In this case, `mod_` components, with a filearea of `intro` are a special case, where they do not use the functions build in file function, and have no itemid.

**Comment by dvdcastro** [comment]
PR #48 has been merged
