### ISSUE TITLE
INT-14731 fix breaks Moodle 3.5 on PHP 7.0

### ISSUE THREAD

**Issue by tonyjbutler** [open-lms-open-source/moodle-tool_ally#49]
The commit https://github.com/blackboard-open-source/moodle-tool_ally/commit/3af9c2f38ae55d82ee9942d03f7479fd932b216d contains a feature introduced in PHP 7.1 (nullable types), and throws an exception in a Moodle 3.5 site running on PHP 7.0 (which is still supported by Moodle 3.5), preventing any pages from loading.

**Comment by tonyjbutler** [comment]
Does this mean INT-14731 is no longer fixed for Moodle 3.5, or is there an alternative fix?

**Comment by dvdcastro** [comment]
Hey @tonyjbutler sorry for the confusion. Ally should work on PHP 7.0 now for the 3.5 version. Specifically, the newly release 3.5.12
https://moodle.org/plugins/pluginversion.php?id=22679

**Comment by tonyjbutler** [comment]
That's great, but is the cron task issue (INT-14731) still fixed now that you've undone the original fix for it?

**Comment by dvdcastro** [comment]
I don't think it should break, I just removed the types and nullables, not the code that fixed the issue. We were having other issues with the tasks, so that's why I added the types in the first place, to see if we could track down the other bugs. Newer versions of the plugin should have further fixes around this.

**Comment by tonyjbutler** [comment]
Ah, I see. That's great, thanks.

**Comment by tonyjbutler** [comment]
... although it looks like you may have missed one: https://github.com/open-lms-open-source/moodle-tool_ally/blob/1dd94e766bd65d1ef2f3b7cc36c81e6e4b93b9d5/classes/componentsupport/interfaces/html_content.php#L47

**Comment by dvdcastro** [comment]
Thanks @tonyjbutler I've just fixed that.

**Comment by dvdcastro** [comment]
The new 3.5.12 version is here: https://moodle.org/plugins/pluginversion.php?id=22682

**Comment by tonyjbutler** [comment]
I've now deployed this to production and the content updates task is still failing with the same exception:
`Coding error detected, it must be fixed by a programmer: $content array should only contain instances of component_content`

**Comment by dvdcastro** [comment]
Hi @tonyjbutler 

Sorry about that, we finally fixed the issue we were having with that task in the 3.6 version on 9e49b95464c04ca14791c5cffda9cd978971e2ab

I've just back-ported the fix in c77d310f9146165aa7816f036535a9c04e6b00f4 and released a new version (3.5.13):
https://moodle.org/plugins/pluginversion.php?id=22726

The problem should be fixed now.
